services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./db/travel_booking.sql/:/docker-entrypoint-initdb.d/travel_booking.sql:ro
      # - ./db/travel_payment.sql/:/docker-entrypoint-initdb.d/travel_payment.sql:ro
      # - ./db/travel_product.sql/:/docker-entrypoint-initdb.d/travel_product.sql:ro
      # - ./db/travel_user.sql/:/docker-entrypoint-initdb.d/travel_user.sql:ro
      # - ./db/create-databases.sql:/docker-entrypoint-initdb.d/create-databases.sql
    networks:
      - dev_network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dev_network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5673:5673"
      - "15673:15673"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - dev_network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - dev_network

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - dev_network

volumes:
  mysql_data:
  mongo_data:
  redis_data:
  rabbitmq_data:

networks:
  dev_network:
    name: dev_network
    driver: bridge