services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./db/travel_booking.sql/:/docker-entrypoint-initdb.d/travel_booking.sql:ro
      # - ./db/travel_payment.sql/:/docker-entrypoint-initdb.d/travel_payment.sql:ro
      # - ./db/travel_product.sql/:/docker-entrypoint-initdb.d/travel_product.sql:ro
      # - ./db/travel_user.sql/:/docker-entrypoint-initdb.d/travel_user.sql:ro
      # - ./db/create-databases.sql:/docker-entrypoint-initdb.d/create-databases.sql
    networks:
      - dev_network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dev_network

  rabbitmq:
    container_name: rabbitmq
    # hostname: rabbitmq-host
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - dev_network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - dev_network

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:latest
    # image: redis/redisinsight:2.42.0
    ports:
      - "5540:5540"
    # volumes:
    #   - redisinsight_data:/data
    networks:
      - dev_network
    depends_on:
      - redis
    restart: unless-stopped


  # mongodb:
  #   container_name: mongodb
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  #   networks:
  #     - dev_network

volumes:
  mysql_data:
  mongo_data:
  redis_data:
  rabbitmq_data:
  redisinsight_data:

networks:
  dev_network:
    name: dev_network
    driver: bridge