# docker-compose up -d
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # import database
      - ./db/travel_booking.sql/:/docker-entrypoint-initdb.d/travel_booking.sql:ro
      - ./db/travel_payment.sql/:/docker-entrypoint-initdb.d/travel_payment.sql:ro
      - ./db/travel_product.sql/:/docker-entrypoint-initdb.d/travel_product.sql:ro
      - ./db/travel_user.sql/:/docker-entrypoint-initdb.d/travel_user.sql:ro
      # - ./db/create-databases.sql:/docker-entrypoint-initdb.d/create-databases.sql
    networks:
      - dev_network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - dev_network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  rabbitmq:
    container_name: rabbitmq
    # hostname: rabbitmq-host
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MGMT_PORT}:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_LOGIN}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - dev_network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mysql
    networks:
      - dev_network

  # redisinsight:
  #   container_name: redisinsight
  #   image: redislabs/redisinsight:latest
  #   # image: redis/redisinsight:2.42.0
  #   ports:
  #     - "${REDISINSIGHT_PORT}:5540"
  #   # volumes:
  #   #   - redisinsight_data:/data
  #   networks:
  #     - dev_network
  #   depends_on:
  #     - redis
  #   restart: unless-stopped


  # mongodb:
  #   container_name: mongodb
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  #   networks:
  #     - dev_network

volumes:
  mysql_data:
  mongo_data:
  redis_data:
  rabbitmq_data:
  redisinsight_data:

networks:
  dev_network:
    name: dev_network
    driver: bridge